# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

production_url : http://nantes-fp.github.com # or your custom domain name
title : Nantes Functional Programming Group

author :
  name : Nantes FP
  email : clement+nantesfp@delafargue.name
  github : nantes-fp
  twitter : nantesfp
